name: Docker Compose Deployment

on:
  workflow_call:
    inputs:
      EC2_SSH_KEY:
        description: 'Private SSH Key for EC2 Access'
        required: true
        type: string
      EC2_HOST:
        description: 'EC2 Host IP or DNS'
        required: true
        type: string
      EC2_USER:
        description: 'EC2 Username'
        required: true
        type: string
      DOCKER_COMPOSE_FILE:
        description: 'Path to the docker-compose.yml file'
        required: true
        type: string
      IMAGE_TAG:
        description: 'Tag for the Docker image (e.g., latest, or branch name)'
        required: true
        type: string
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2
 
      # Build Docker images for auth-service and api-gateway
      - name: Build Docker images
        run: |
          docker build -t api-gateway:v0.0.1 . # Adjust path as needed
        # docker build -t api-gateway:${{ inputs.IMAGE_TAG }} ./api-gateway  # Adjust path as needed
 
      # Set up SSH private key for EC2 access

      # - name: Check SSH Key
      #   run: |
      #     echo "${{ secrets.EC2_SSH_KEY }}"
 
      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ inputs.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          EC2_SSH_KEY: ${{ inputs.EC2_SSH_KEY }}
 
      # - name: Copy Docker image to EC2
      #   uses: appleboy/scp-action@v0.1.3
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     Username: ${{ secrets.EC2_USER }}
      #     KEY: ${{ secrets.EC2_SSH_KEY }}
      #     target: /home/ubuntu/
 
      - name: Load Docker image on EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ inputs.EC2_HOST }}
          Username: ${{ inputs.EC2_USER }}
          KEY: ${{ inputs.EC2_SSH_KEY }}
          script: docker load -i /home/ubuntu/api-gateway:v0.0.1
          debug: true
         
 
      # Deploy Docker Compose to EC2
      - name: Deploy Docker Compose to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "${{ inputs.EC2_USER }}"@"${{ inputs.EC2_HOST }}" << 'EOF
            cd /home/ubuntu/rehab
            docker-compose pull  
            docker-compose up -d  
          EOF